# Copyright © 2018 Amdocs, Bell Canada, AT&T
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
dependencies:
  - name: common
    version: ~5.x-0
    # local reference to common chart, as it is
    # a part of this chart's package and will not
    # be published independently to a repo (at this point)
    repository: '@local'
  - name: cassandra
    version: ~5.x-0
    # local reference to common chart, as it is
    # a part of this chart's package and will not
    # be published independently to a repo (at this point)
    repository: '@local'
    condition: global.cassandra.localCluster
  - name: aai-babel
    version: ~5.x-0
    repository: 'file://components/aai-babel'
    condition: aai-babel.enabled
  - name: aai-champ
    version: ~5.x-0
    repository: 'file://components/aai-champ'
    condition: aai-champ.enabled
  - name: aai-data-router
    version: ~5.x-0
    repository: 'file://components/aai-data-router'
    condition: aai-data-router.enabled
  - name: aai-elasticsearch
    version: ~5.x-0
    repository: 'file://components/aai-elasticsearch'
    condition: aai-elasticsearch.enabled
  - name: aai-gizmo
    version: ~5.x-0
    repository: 'file://components/aai-gizmo'
    condition: aai-gizmo.enabled
  - name: aai-graphadmin
    version: ~5.x-0
    repository: 'file://components/aai-graphadmin'
    condition: aai-graphadmin.enabled
  - name: aai-modelloader
    version: ~5.x-0
    repository: 'file://components/aai-modelloader'
    condition: aai-modelloader.enabled
  - name: aai-resources
    version: ~5.x-0
    repository: 'file://components/aai-resources'
    condition: aai-resources.enabled
  - name: aai-schema-service
    version: ~5.x-0
    repository: 'file://components/aai-schema-service'
    condition: aai-schema-service.enabled
  - name: aai-search-data
    version: ~5.x-0
    repository: 'file://components/aai-search-data'
    condition: aai-search-data.enabled
  - name: aai-sparky-be
    version: ~5.x-0
    repository: 'file://components/aai-sparky-be'
    condition: aai-sparky-be.enabled
  - name: aai-spike
    version: ~5.x-0
    repository: 'file://components/aai-spike'
    condition: aai-spike.enabled
  - name: aai-traversal
    version: ~5.x-0
    repository: 'file://components/aai-traversal'
    condition: aai-traversal.enabled
  - name: aai-graphgraph
    version: ~5.x-0
    repository: 'file://components/aai-graphgraph'
    condition: aai-graphgraph.enabled
