# Copyright © 2018 Amdocs, AT&T
# Modifications Copyright © 2018 Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#################################################################
# Global configuration defaults.
#################################################################
global:
  loggingImage: beats/filebeat:5.5.0

#################################################################
# Application configuration defaults.
#################################################################

# application image
image: onap/babel:1.6.2

flavor: small

# application configuration
config:
  keyStorePassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
  keyManagerPassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: false

readiness:
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  type: NodePort
  portName: babel
  externalPort: 9516
  internalPort: 9516
  nodePort: 79

ingress:
  enabled: false
  service:
    - baseaddr: "aaibabel"
      name: "aai-babel"
      port: 9516
  config:
    ssl: "redirect"

log:
  root:
    level: INFO
  consolePattern:
    babel:
      config: "%nopexception${p_log}\t${p_tim}\t${p_lvl}\t%message\t${p_mdc}\t%rootException\t${p_mak}\t${p_thr}%n"
      fproxy: "%d{ISO8601} %-5level [%t] %C{1.}: %msg%n%throwable"
      rproxy: "%d{ISO8601} %-5level [%t] %C{1.}: %msg%n%throwable"
  logger:
    apache: WARN
    apacheCamel: WARN
    apacheCamelComponentRestlet: WARN
    apacheCamelProcessorInterceptor: WARN
    apacheCommons: WARN
    apacheCxf: WARN
    apacheCxfJaxrsInterceptor: WARN
    apacheCxfService: WARN
    att: INFO
    qosLogbackClassic: WARN
    qosLogbackCore: WARN
    restlet: WARN
    springframework: WARN
    springframeworkBeans: WARN
    springframeworkWeb: WARN

resources:
  small:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0.5
      memory: 1Gi
  large:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 2Gi
  unlimited: {}
