# Copyright © 2018 Amdocs, AT&T
# Modifications Copyright © 2018 Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#################################################################
# Global configuration defaults.
#################################################################
global:
  readinessImage: readiness-check:2.0.2
  loggingImage: beats/filebeat:5.5.0
  repository: nexus3.onap.org:10001

#################################################################
# Application configuration defaults.
#################################################################

# application image
repository: nexus3.onap.org:10001
image: onap/babel:1.4.2
pullPolicy: Always

flavor: small

# application configuration
config:
  keyStorePassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
  keyManagerPassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10

configMaps:
  - name: '{{ include "common.fullname" . }}-configmap'
    filePath: "resources/config/*"

secrets:
  - name: '{{ include "common.fullname" . }}-babel-secrets'
    filePath: "resources/config/auth/*"
  - name: '{{ include "common.fullname" . }}-pass'
    envs:
      - name: KEY_STORE_PASSWORD
        value: '{{ .Values.config.keyStorePassword | b64enc | quote }}'
      - name: KEY_MANAGER_PASSWORD
        value: '{{ .Values.config.keyManagerPassword | b64enc | quote }}'

secretFileName: "secrets.yaml"

envs:
  - name: CONFIG_HOME
    value: /opt/app/babel/config
  - name: KEY_STORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: '{{ template "common.fullname" . }}-pass'
        key: KEY_STORE_PASSWORD
  - name: KEY_MANAGER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: '{{ template "common.fullname" . }}-pass'
        key: KEY_MANAGER_PASSWORD

volumeMounts:
  - mountPath: /opt/app/babel/config/artifact-generator.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: artifact-generator.properties
  - mountPath: /opt/app/babel/config/tosca-mappings.json
    name: '{{ include "common.fullname" . }}-config'
    subPath: tosca-mappings.json
  - mountPath: /opt/app/babel/config/babel-auth.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: babel-auth.properties
  - mountPath: /opt/app/babel/config/auth
    name: '{{ include "common.fullname" . }}-secrets'
  - mountPath: /var/log/onap
    name: '{{ include "common.fullname" . }}-logs'
  - mountPath: /opt/app/babel/config/logback.xml
    name: '{{ include "common.fullname" . }}-config'
    subPath: logback.xml

volumes:
  - volumeMountRefName: '{{ include "common.fullname" . }}-config'
    name: '{{ include "common.fullname" . }}-configmap'
    type: configMap
    items:
      - key: artifact-generator.properties
        path: artifact-generator.properties
      - key: tosca-mappings.json
        path: tosca-mappings.json
      - key: babel-auth.properties
        path: babel-auth.properties
      - key: logback.xml
        path: logback.xml
  - volumeMountRefName: '{{ include "common.fullname" . }}-secrets'
    name: '{{ include "common.fullname" . }}-babel-secrets'
    type: secret
  - volumeMountRefName: filebeat-conf
    name: aai-filebeat
    type: configMap
  - volumeMountRefName: '{{ include "common.fullname" . }}-logs'
    type: emptyDir
  - volumeMountRefName: aai-filebeat
    type: emptyDir

sideCarContainers:
 - name: filebeat-onap
   image: '{{ .Values.global.loggingRepository }}/{{ .Values.global.loggingImage }}'
   imagePullPolicy: '{{ .Values.global.pullPolicy | default .Values.pullPolicy }}'
   volumeMounts:
   - mountPath: /usr/share/filebeat/filebeat.yml
     subPath: filebeat.yml
     name: filebeat-conf
   - mountPath: /var/log/onap
     name: '{{ include "common.fullname" . }}-logs'
   - mountPath: /usr/share/filebeat/data
     name: aai-filebeat

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: false

readiness:
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  type: NodePort
  portName: babel
  externalPort: 9516
  internalPort: 9516
  nodePort: 79

ingress:
  enabled: false

resources:
  small:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  large:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 2Gi
  unlimited: {}
