# Copyright © 2018 Amdocs, Bell Canada, AT&T
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for data-router.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: # global defaults
  nodePortPrefix: 302
  loggingImage: beats/filebeat:5.5.0

# application image
repository: nexus3.onap.org:10001
image: onap/data-router:1.4.0
pullPolicy: Always
restartPolicy: Always
flavor: small
dockerhubRepository: registry.hub.docker.com
ubuntuInitImage: oomk8s/ubuntu-init:2.0.0

# application configuration
config:
  keyStorePassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
  keyManagerPassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
  schemaTranslatorList: config

configMaps:
  - name: '{{ include "common.fullname" . }}-prop'
    filePath: "resources/config/*"
  - name: '{{ include "common.fullname" . }}-dynamic'
    filePaths:
      - "resources/dynamic/routes/entity-event.route"
      - "resources/dynamic/conf/data-router-oxm.xml"
      - "resources/dynamic/conf/entity-event-policy.xml"
  - name: '{{ include "common.fullname" . }}-log-configmap'
    filePath: "resources/config/log/*"
  - name: '{{ include "common.fullname" . }}-filebeat-configmap'
    filePath: "resources/config/log/filebeat/*"

secrets:
  - name: '{{ include "common.fullname" . }}'
    filePath: "resources/config/auth/*"

envs:
  - name: SERVICE_BEANS
    value: /opt/app/data-router/dynamic/conf
  - name: CONFIG_HOME
    value: /opt/app/data-router/config/
  - name: KEY_STORE_PASSWORD
    value: '{{ .Values.config.keyStorePassword }}'
  - name: DYNAMIC_ROUTES
    value: /opt/app/data-router/dynamic/routes
  - name: KEY_MANAGER_PASSWORD
    value: '{{ .Values.config.keyManagerPassword }}'
  - name: PATH
    value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - name: JAVA_HOME
    value: usr/lib/jvm/java-8-openjdk-amd64

volumeMounts:
  - mountPath:  /opt/app/data-router/config/auth
    name: '{{ include "common.fullname" . }}-auth'
  - mountPath:  /opt/app/data-router/config/data-router.properties
    subPath: data-router.properties
    name: '{{ include "common.fullname" . }}-properties'
  - mountPath:  /opt/app/data-router/config/schemaIngest.properties
    subPath: schemaIngest.properties
    name: '{{ include "common.fullname" . }}-properties'
  - mountPath: /opt/app/data-router/dynamic/routes/entity-event.route
    subPath: entity-event.route
    name: '{{ include "common.fullname" . }}-dynamic-route'
  - mountPath: /opt/app/data-router/dynamic/conf/entity-event-policy.xml
    subPath: entity-event-policy.xml
    name: '{{ include "common.fullname" . }}-dynamic-policy'
  - mountPath: /opt/app/data-router/dynamic/conf/data-router-oxm.xml
    subPath: data-router-oxm.xml
    name: '{{ include "common.fullname" . }}-dynamic-oxm'
  - mountPath: /opt/app/data-router/bundleconfig/etc/logback.xml
    name: '{{ include "common.fullname" . }}-logback-config'
    subPath: logback.xml
  - mountPath: /var/log/onap
    name: '{{ include "common.fullname" . }}-logs'
  - mountPath: /logs
    name: '{{ include "common.fullname" . }}-logs'

volumes:
  - volumeMountRefName: filebeat-conf
    name: aai-filebeat
    type: configMap
  - volumeMountRefName: aai-filebeat
    type: emptyDir
  - name: '{{ include "common.fullname" . }}'
    volumeMountRefName: '{{ include "common.fullname" . }}-auth'
    type: secret
  - name: '{{ include "common.fullname" . }}-prop'
    volumeMountRefName: '{{ include "common.fullname" . }}-properties'
    type: configMap
    items:
      - key: data-router.properties
        path: data-router.properties
      - key: schemaIngest.properties
        path: schemaIngest.properties
  - name: '{{ include "common.fullname" . }}-dynamic'
    volumeMountRefName: '{{ include "common.fullname" . }}-dynamic-route'
    type: configMap
  - name: '{{ include "common.fullname" . }}-dynamic'
    volumeMountRefName: '{{ include "common.fullname" . }}-dynamic-policy'
    type: configMap
  - name: '{{ include "common.fullname" . }}-dynamic'
    volumeMountRefName: '{{ include "common.fullname" . }}-dynamic-oxm'
    type: configMap
  - volumeMountRefName: '{{ include "common.fullname" . }}-logs'
    type: emptyDir
  - name: '{{ include "common.fullname" . }}-log-configmap'
    volumeMountRefName: '{{ include "common.fullname" . }}-logback-config'
    type: configMap
    items:
      - key: logback.xml
        path: logback.xml

sideCarContainers:
  - name: filebeat-onap
    image: '{{ .Values.global.loggingRepository }}/{{ .Values.global.loggingImage }}'
    imagePullPolicy: '{{ .Values.global.pullPolicy | default .Values.pullPolicy }}'
    volumeMounts:
      - mountPath: /usr/share/filebeat/filebeat.yml
        subPath: filebeat.yml
        name: filebeat-conf
      - mountPath: /var/log/onap
        name: '{{ include "common.fullname" . }}-logs'
    - mountPath: /logs
      name: '{{ include "common.fullname" . }}-logs'
    - mountPath: /usr/share/filebeat/data
      name: aai-filebeat

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  name: aai-data-router
  internalPort: 9502

ingress:
  enabled: false

persistence:
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  volumeReclaimPolicy: Retain

  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  ## storageClass: "-"
  accessMode: ReadWriteMany
  size: 2Gi
  mountPath: /dockerdata-nfs
  mountSubPath: aai/data-router/logs

resources:
  small:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0.25
      memory: 750Mi
  large:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 0.5
      memory: 1536Mi
  unlimited: {}

# Entity Event route configuration
event:
  port:
    dmaap: 3905
  protocol: https
  consumer:
    topic: AAI-EVENT
