# Copyright © 2018 Amdocs, Bell Canada, AT&T
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for traversal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: # global defaults
  nodePortPrefix: 302
  readinessRepository: oomk8s
  readinessImage: readiness-check:2.0.2
  repository: nexus3.onap.org:10001


# application image
repository: nexus3.onap.org:10001
image: onap/aai-traversal:1.5.0
pullPolicy: Always
restartPolicy: Always
flavor: small

annotations:
  msb.onap.org/service-info: '[
    {
        "serviceName": "_aai-generic-query",
        "version": "v11",
        "url": "/aai/v11/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v11/search/generic-query"
    },
    {
        "serviceName": "_aai-generic-query",
        "version": "v12",
        "url": "/aai/v12/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v12/search/generic-query"
    },
    {
        "serviceName": "_aai-generic-query",
        "version": "v13",
        "url": "/aai/v13/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v13/search/generic-query"
    },
    {
        "serviceName": "_aai-generic-query",
        "version": "v14",
        "url": "/aai/v14/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v14/search/generic-query"
    },
    {
        "serviceName": "_aai-generic-query",
        "version": "v15",
        "url": "/aai/v15/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v15/search/generic-query"
    },
    {
        "serviceName": "_aai-generic-query",
        "version": "v16",
        "url": "/aai/v16/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v16/search/generic-query"
    },
    {
        "serviceName": "_aai-nodes-query",
        "version": "v11",
        "url": "/aai/v11/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v11/search/nodes-query"
    },
    {
        "serviceName": "_aai-nodes-query",
        "version": "v12",
        "url": "/aai/v12/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v12/search/nodes-query"
    },
    {
        "serviceName": "_aai-nodes-query",
        "version": "v13",
        "url": "/aai/v13/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v13/search/nodes-query"
    },
    {
        "serviceName": "_aai-nodes-query",
        "version": "v14",
        "url": "/aai/v14/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v14/search/nodes-query"
    },
    {
        "serviceName": "_aai-nodes-query",
        "version": "v15",
        "url": "/aai/v15/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v15/search/nodes-query"
    },
    {
        "serviceName": "_aai-nodes-query",
        "version": "v16",
        "url": "/aai/v16/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v16/search/nodes-query"
    },
    {
        "serviceName": "_aai-query",
        "version": "v11",
        "url": "/aai/v11/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v11/query"
    },
    {
        "serviceName": "_aai-query",
        "version": "v12",
        "url": "/aai/v12/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v12/query"
    },
    {
        "serviceName": "_aai-query",
        "version": "v13",
        "url": "/aai/v13/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v13/query"
    },
    {
        "serviceName": "_aai-query",
        "version": "v14",
        "url": "/aai/v14/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v14/query"
    },
    {
        "serviceName": "_aai-query",
        "version": "v15",
        "url": "/aai/v15/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v15/query"
    },
    {
        "serviceName": "_aai-query",
        "version": "v16",
        "url": "/aai/v16/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/v16/query"
    },
    {
        "serviceName": "_aai-named-query",
        "url": "/aai/search",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1",
        "path": "/aai/search"
    },
    {
        "serviceName": "aai-generic-query",
        "version": "v11",
        "url": "/aai/v11/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-generic-query",
        "version": "v12",
        "url": "/aai/v12/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-generic-query",
        "version": "v13",
        "url": "/aai/v13/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-generic-query",
        "version": "v14",
        "url": "/aai/v14/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-generic-query",
        "version": "v15",
        "url": "/aai/v15/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-generic-query",
        "version": "v16",
        "url": "/aai/v16/search/generic-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-nodes-query",
        "version": "v11",
        "url": "/aai/v11/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-nodes-query",
        "version": "v12",
        "url": "/aai/v12/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-nodes-query",
        "version": "v13",
        "url": "/aai/v13/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-nodes-query",
        "version": "v14",
        "url": "/aai/v14/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-nodes-query",
        "version": "v15",
        "url": "/aai/v15/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-nodes-query",
        "version": "v16",
        "url": "/aai/v16/search/nodes-query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-query",
        "version": "v11",
        "url": "/aai/v11/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-query",
        "version": "v12",
        "url": "/aai/v12/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-query",
        "version": "v13",
        "url": "/aai/v13/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-query",
        "version": "v14",
        "url": "/aai/v14/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-query",
        "version": "v15",
        "url": "/aai/v15/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-query",
        "version": "v16",
        "url": "/aai/v16/query",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    },
    {
        "serviceName": "aai-named-query",
        "url": "/aai/search",
        "protocol": "REST",
        "port": "8446",
        "enable_ssl": true,
        "lb_policy":"ip_hash",
        "visualRange": "1"
    }
    ]'


initContainers:
  enabled: true
  containerList:
    - aai-schema-service
    - aai-resources

configMaps:
  - name: '{{ include "common.fullname" . }}-configmap'
    filePaths:
      - "resources/config/logback.xml"
      - "resources/config/localhost-access-logback.xml"
      - "resources/config/janusgraph-realtime.properties"
      - "resources/config/janusgraph-cached.properties"
      - "resources/config/aaiconfig.properties"
      - "resources/config/application.properties"
      - "resources/config/realm.properties"
  - name: '{{ include "common.fullname" . }}-aaf-props'
    filePaths:
      - "resources/config/aaf/org.osaaf.location.props"
      - "resources/config/aaf/permissions.properties"
      - "resources/config/aaf/org.onap.aai.props"
      - "resources/config/aaf/cadi.properties"

secrets:
  - name: '{{ include "common.fullname" . }}-aaf-keys'
    filePaths:
      - "resources/config/aaf/org.onap.aai.keyfile"
      - "resources/config/aaf/org.onap.aai.p12"
      - "resources/config/aaf/bath_config.csv"

volumeMounts:
  - mountPath: /opt/app/aai-traversal/resources/etc/appprops/janusgraph-realtime.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: janusgraph-realtime.properties
  - mountPath: /opt/app/aai-traversal/resources/etc/appprops/janusgraph-cached.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: janusgraph-cached.properties
  - mountPath: /opt/app/aai-traversal/resources/etc/appprops/aaiconfig.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: aaiconfig.properties
  - mountPath: /opt/aai/logroot/AAI-GQ
    name: '{{ include "common.fullname" . }}-logs'
  - mountPath: /opt/app/aai-traversal/resources/logback.xml
    name: '{{ include "common.fullname" . }}-config'
    subPath: logback.xml
  - mountPath: /opt/app/aai-traversal/resources/localhost-access-logback.xml
    name: '{{ include "common.fullname" . }}-config'
    subPath: localhost-access-logback.xml
  - mountPath: /opt/app/aai-traversal/resources/etc/auth/realm.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: realm.properties
  - mountPath: /opt/app/aai-traversal/resources/aaf/org.onap.aai.keyfile
    name: '{{ include "common.fullname" . }}-aaf-certs'
    subPath: org.onap.aai.keyfile
  - mountPath: /opt/app/aai-traversal/resources/aaf/bath_config.csv
    name: '{{ include "common.fullname" . }}-aaf-certs'
    subPath: bath_config.csv
  - mountPath: /opt/app/aai-traversal/resources/aaf/org.onap.aai.props
    name: '{{ include "common.fullname" . }}-aaf-properties'
    subPath: org.onap.aai.props
  - mountPath: /opt/app/aai-traversal/resources/aaf/org.osaaf.location.props
    name: '{{ include "common.fullname" . }}-aaf-properties'
    subPath: org.osaaf.location.props
  - mountPath: /opt/app/aai-traversal/resources/aaf/permissions.properties
    name: '{{ include "common.fullname" . }}-aaf-properties'
    subPath: permissions.properties
  - mountPath: /opt/app/aai-traversal/resources/cadi.properties
    name: '{{ include "common.fullname" . }}-aaf-properties'
    subPath: cadi.properties
  - mountPath: /opt/app/aai-traversal/resources/aaf/org.onap.aai.p12
    name: '{{ include "common.fullname" . }}-aaf-certs'
    subPath: org.onap.aai.p12
  - mountPath: /opt/app/aai-traversal/resources/aaf/truststoreONAPall.jks
    name: aai-common-aai-auth
    subPath: truststoreONAPall.jks
  - mountPath: /opt/app/aai-traversal/resources/application.properties
    name: '{{ include "common.fullname" . }}-config'
    subPath: application.properties
  - mountPath: /opt/app/aai-traversal/resources/etc/auth/aai_keystore
    name: '{{ include "common.fullname" . }}-auth-truststore-sec'
    subPath: aai_keystore

volumes:
  - volumeMountRefName: filebeat-conf
    type: configMap
    name: aai-filebeat
  - volumeMountRefName: '{{ include "common.fullname" . }}-logs'
    type: emptyDir
  - volumeMountRefName: '{{ include "common.fullname" . }}-filebeat'
    type: emptyDir
  - volumeMountRefName: '{{ include "common.fullname" . }}-config'
    type: configMap
    name: '{{ include "common.fullname" . }}-configmap'
  - volumeMountRefName: '{{ include "common.fullname" . }}-aaf-properties'
    type: configMap
    name: '{{ include "common.fullname" . }}-aaf-props'
  - volumeMountRefName: '{{ include "common.fullname" . }}-aaf-certs'
    type: secret
    name: '{{ include "common.fullname" . }}-aaf-keys'
  - volumeMountRefName: aai-common-aai-auth
    type: secret
    name: aai-common-aai-auth
  - volumeMountRefName: '{{ include "common.fullname" . }}-auth-truststore-sec'
    type: secret
    name: aai-common-truststore

sideCarContainers:
  - name: filebeat-onap
    image: '{{ .Values.global.loggingRepository }}/{{ .Values.global.loggingImage }}'
    imagePullPolicy: '{{ .Values.global.pullPolicy | default .Values.pullPolicy }}'
    volumeMounts:
      - mountPath: /usr/share/filebeat/filebeat.yml
        subPath: filebeat.yml
        name: filebeat-conf
      - mountPath: /var/log/onap
        name: '{{ include "common.fullname" . }}-logs'
      - mountPath: /usr/share/filebeat/data
        name: '{{ include "common.fullname" . }}-filebeat'

# application configuration
config:

  # Specifies timeout information such as application specific and limits
  timeout:
    # If set to true application will timeout for queries taking longer than limit
    enabled: true
    # Specifies which apps (X-FromAppId) header should get overridden and (-1) no timeout
    appspecific: JUNITTESTAPP1,1|JUNITTESTAPP2,-1|DCAE-CCS,-1|DCAES,-1|AAI-FILEGEN-GFPIP,-1
    # Specifies how long should it wait before timing out the REST request
    limit: 180000

  # Disables the updateQueryData script to run as part of traversal
  disableUpdateQuery: true

  # Override of the DSL Timeout Limit
  dslOverride: 'ZV4V7E3N77SKIB6MR9MHQ6M4P6Q99Z7M76RBODA'

  dsl:
    # Dsl timeout configuration
    timeout:
      # Whether or not the dsl is enabled
      enabled: true
      # Default time limit of the DSL query
      limit: 150000
      # App Specific Timeout Limit for each of the X-FromAppId
      appspecific:
        - JUNITTESTAPP1,1
        - JUNITTESTAPP2,-1
        - AAI-TOOLS,-1
        - DCAE-CCS,1200000
        - DCAES,1200000
        - VPESAT,-1
        - AAI-CACHER,-1
        - VidAaiController,300000
        - AAI-UI,180000

persistence:
  mountPath: /dockerdata-nfs
  mountSubPath: aai/aai-traversal

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 60
  periodSeconds: 60
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: false

readiness:
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  type: ClusterIP
  portName: aai-traversal-8446
  internalPort: 8446
  portName2: aai-traversal-5005
  internalPort2: 5005

ingress:
  enabled: false

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  small:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 3Gi
  large:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  unlimited: {}
