# Copyright © 2018 Amdocs, AT&T
# Modifications Copyright © 2018 Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#################################################################
global:
  nodePortPrefix: 302
  loggingImage: beats/filebeat:5.5.0

#################################################################
# Application configuration defaults.
#################################################################

# application image
image: onap/gizmo:1.4.0
flavor: small
# application configuration
config:
  keyStorePassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
  keyManagerPassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10
  trustStorePassword: OBF:1y0q1uvc1uum1uvg1pil1pjl1uuq1uvk1uuu1y10

configMaps:
  - name: '{{ include "common.fullname" . }}-configmap'
    filePath: "resources/config/*"
  - name: '{{ include "common.fullname" . }}-model-configmap'
    filePath: "resources/config/model/*"
  - name: '{{ include "common.fullname" . }}-log-configmap'
    filePath: "resources/config/log/*"
  - name: '{{ include "common.fullname" . }}-filebeat-configmap'
    filePath: "resources/config/log/filebeat/*"

secrets:
  - name: '{{ include "common.fullname" . }}-auth'
    filePath: "resources/config/auth/*"
  - name: '{{ include "common.fullname" . }}-pass'
    envs:
      - name: KEY_STORE_PASSWORD
        value: '{{ .Values.config.keyStorePassword | b64enc | quote }}'
      - name: KEY_MANAGER_PASSWORD
        value: '{{ .Values.config.keyManagerPassword | b64enc | quote }}'
envs:
  - name: CONFIG_HOME
    value: /opt/app/crud-service/config/
  - name: KEY_STORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: '{{ template "common.fullname" . }}-pass'
        key: KEY_STORE_PASSWORD
  - name: KEY_MANAGER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: '{{ template "common.fullname" . }}-pass'
        key: KEY_MANAGER_PASSWORD
  - name: SERVICE_BEANS
    value: /opt/app/crud-service/dynamic/conf

volumeMounts:
  - mountPath: /opt/app/crud-service/config/crud-api.properties
    subPath: crud-api.properties
    name: '{{ include "common.fullname" . }}-config'
  - mountPath: /opt/app/crud-service/config/schema-ingest.properties
    subPath: schema-ingest.properties
    name: '{{ include "common.fullname" . }}-config'
  - mountPath: /opt/app/crud-service/config/edgeprops-ingest.properties
    subPath: edgeprops-ingest.properties
    name: '{{ include "common.fullname" . }}-config'
  - mountPath: /opt/app/crud-service/config/model/
    name: '{{ include "common.fullname" . }}-model-config'
  - mountPath: /opt/app/crud-service/config/auth
    name: '{{ include "common.fullname" . }}-auth-secret'
  - mountPath: /opt/app/crud-service/dynamic/conf/crud-beans.xml
    name: '{{ include "common.fullname" . }}-config'
    subPath: crud-beans.xml
  - mountPath: /var/log/onap
    name: '{{ include "common.fullname" . }}-logs'
  - mountPath: /opt/app/crud-api/bundleconfig/etc/logback.xml
    name: '{{ include "common.fullname" . }}-logback-config'
    subPath: logback.xml

volumes:
  - volumeMountRefName: '{{ include "common.fullname" . }}-filebeat'
    type: emptyDir
  - volumeMountRefName: '{{ include "common.fullname" . }}-logs'
    type: emptyDir
  - volumeMountRefName: '{{ include "common.fullname" . }}-auth-secret'
    type: secret
    name: '{{ include "common.fullname" . }}-auth'
  - volumeMountRefName: '{{ include "common.fullname" . }}-config'
    type: configMap
    name: '{{ include "common.fullname" . }}-configmap'
    items:
      - key: crud-api.properties
        path: crud-api.properties
      - key: schema-ingest.properties
        path: schema-ingest.properties
      - key: edgeprops-ingest.properties
        path: edgeprops-ingest.properties
      - key: crud-beans.xml
        path: crud-beans.xml
  - volumeMountRefName: '{{ include "common.fullname" . }}-logback-config'
    type: configMap
    name: '{{ include "common.fullname" . }}-log-configmap'
    items:
      - key: logback.xml
        path: logback.xml
  - volumeMountRefName: '{{ include "common.fullname" . }}-model-config'
    type: configMap
    name: '{{ include "common.fullname" . }}-model-configmap'
  - volumeMountRefName: filebeat-conf
    type: configMap
    name: aai-filebeat

secretFileName: "secrets.yaml"

sideCarContainers:
  - name: filebeat-onap
    image: '{{ .Values.global.loggingRepository }}/{{ .Values.global.loggingImage }}'
    imagePullPolicy: '{{ .Values.global.pullPolicy | default .Values.pullPolicy }}'
    volumeMounts:
      - mountPath: /usr/share/filebeat/filebeat.yml
        name: filebeat-conf
        subPath: filebeat.yml
      - mountPath: /var/log/onap
        name: '{{ include "common.fullname" . }}-logs'
      - mountPath: /usr/share/filebeat/data
        name: '{{ include "common.fullname" . }}-filebeat'

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 60
  timeoutSeconds: 10
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 60
  timeoutSeconds: 10
  periodSeconds: 10

service:
  type: NodePort
  name: aai-crud-service
  portName: aai-crud-service
  internalPort: 9520
  externalPort: 9520
  nodePort: 68

ingress:
  enabled: false

resources:
  small:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0.5
      memory: 1Gi
  large:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1
      memory: 1536Mi
  unlimited: {}
