# Copyright © 2018 Amdocs, Bell Canada, AT&T
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for modelloader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: # global defaults
  nodePortPrefix: 302
  repository: nexus3.onap.org:10001


# application image
repository: nexus3.onap.org:10001
image: onap/model-loader:1.4.0
pullPolicy: Always
restartPolicy: Always
flavor: small
# application configuration
config: {}

configMaps:
  - name: '{{ include "common.fullname" . }}-prop'
    filePath: "resources/config/model-loader.properties"
  - name: '{{ include "common.fullname" . }}-log'
    filePath: "resources/config/log/logback.xml"

envs:
  - name: CONFIG_HOME
    value: /opt/app/model-loader/config/

secrets:
  - name: '{{ include "common.fullname" . }}'
    filePath: "resources/config/auth/*"

volumeMounts:
  - mountPath: /opt/app/model-loader/config/model-loader.properties
    subPath: model-loader.properties
    name: '{{ include "common.fullname" . }}-prop-config'
  - mountPath: /opt/app/model-loader/config/auth/
    name: '{{ include "common.fullname" . }}-auth-config'
  - mountPath: /var/log/onap
    name: '{{ include "common.fullname" . }}-logs'
  - mountPath: /opt/app/model-loader/logback.xml
    name: '{{ include "common.fullname" . }}-log-conf'
    subPath: logback.xml

volumes:
  - volumeMountRefName: '{{ include "common.fullname" . }}-prop-config'
    type: configMap
    name: '{{ include "common.fullname" . }}-prop'
  - volumeMountRefName: '{{ include "common.fullname" . }}-auth-config'
    type: secret
    name: '{{ include "common.fullname" . }}'
  - volumeMountRefName: filebeat-conf
    type: configMap
    name: aai-filebeat
  - volumeMountRefName: '{{ include "common.fullname" . }}-logs'
    type: emptyDir
  - volumeMountRefName: filebeat-data
    type: emptyDir
  - volumeMountRefName: '{{ include "common.fullname" . }}-log-conf'
    type: configMap
    name: '{{ include "common.fullname" . }}-log'


sideCarContainers:
  - name: filebeat-onap
    image: '{{ .Values.global.loggingRepository }}/{{ .Values.global.loggingImage }}'
    imagePullPolicy: '{{ .Values.global.pullPolicy | default .Values.pullPolicy }}'
    volumeMounts:
      - mountPath: /usr/share/filebeat/filebeat.yml
        subPath: filebeat.yml
        name: filebeat-conf
      - mountPath: /var/log/onap
        name: '{{ include "common.fullname" . }}-logs'
      - mountPath: /usr/share/filebeat/data
        name: filebeat-data

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  type: NodePort
  portName: aai-modelloader
  externalPort: 8080
  internalPort: 8080
  nodePort: 10
  portName2: aai-modelloader-ssl
  externalPort2: 8443
  internalPort2: 8443
  nodePort2: 29

ingress:
  enabled: false


resources:
  small:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  large:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 1536Mi
  unlimited: {}
